name: 01-Hello-World

# 1. 触发器：什么时候跑？
on: [push] 

jobs:
  # 2. 定义任务 ID
  say-hello:
    # 3. 运行环境：给我一台 Ubuntu 虚拟机
    runs-on: ubuntu-latest
    
    # 4. 步骤：具体干什么
    steps:
      - name: 打个招呼
        run: echo "Hello, CI/CD! 这里的每一行都是 shell 命令。"
      
      - name: 查看环境信息
        run: |
          echo "我是谁："
          whoami
          echo "我在哪："
          pwd
          echo "机器配置："
          lscpu | grep "Model name"